/* Create tables for the processed data */
/* This file creates tables using corrected normalisation tables */

CREATE TABLE salfordMove.dbo.APPLICATIONS(
	applicationID INT NOT NULL,
	applicationName NVARCHAR(10),
	CONSTRAINT PK_APPLICATIONS PRIMARY KEY (applicationID)
);

CREATE TABLE salfordMove.dbo.NETWORKS(
	networkID INT NOT NULL,
	networkName NVARCHAR(10),
	CONSTRAINT PK_NETWORKS PRIMARY KEY (networkID)
);

CREATE TABLE salfordMove.dbo.SENSORS(
	sensorID INT NOT NULL,
	applicationID INT NOT NULL,
	networkID INT NOT NULL,
	sensorName NVARCHAR(MAX),
	CONSTRAINT PK_SENSORS PRIMARY KEY (sensorID),
	CONSTRAINT FK_SENSORS_APPLICATIONS FOREIGN KEY (applicationID)
	REFERENCES salfordMove.dbo.APPLICATIONS (applicationID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_SENSORS_NETWORKS FOREIGN KEY (networkID)
	REFERENCES salfordMove.dbo.NETWORKS (networkID)
	ON DELETE CASCADE
	on UPDATE CASCADE
);

CREATE TABLE salfordMove.dbo.DATA_TYPES(
	dTypeID INT NOT NULL,
	dataType NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_DATA_TYPES PRIMARY KEY (dTypeID)
);

CREATE TABLE salfordMove.dbo.READINGS(
	readingID INT NOT NULL,
	dataMessageGUID GUID NOT NULL,
	sensorID INT NOT NULL,
	dTypeID INT NOT NULL,
	reading NVARCHAR(5) NOT NULL,
	messageType NVARCHAR(5),
	CONSTRAINT PK_READINGS PRIMARY KEY (readingID),
	CONSTRAINT PK_READINGS_GUID PRIMARY KEY (dataMessageGUID),
	CONSTRAINT FK_READINGS_SENSORS FOREIGN KEY (sensorID)
	REFERENCES salfordMove.dbo.SENSORS (sensorID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_READINGS_DTYPE FOREIGN KEY (dTypeID)
	REFERENCES salfordMove.dbo.DATA_TYPES (dTypeID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE salfordMove.dbo.SIGNAL_STATUS(
	signalID INT NOT NULL,
	dataMessageGUID GUID NOT NULL,
	signalStrength FLOAT,
	CONSTRAINT PK_SIGNAL_STATUS PRIMARY KEY (signalID),
	CONSTRAINT FK_SIGNAL_STATUS_GUID FOREIGN KEY (dataMessageGUID)
	REFERENCES salfordMove.dbo.SENSORS (dataMessageGUID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)

CREATE TABLE salfordMove.dbo.BATTERY_STATUS(
	batteryID INT NOT NULL,
	dataMessageGUID GUID NOT NULL,
	batteryLevel INT,
	CONSTRAINT PK_BATTERY_STATUS PRIMARY KEY (batteryID),
	CONSTRAINT FK_BATTERY_STATUS_GUID FOREIGN KEY (dataMessageGUID)
	REFERENCES salfordMove.dbo.SENSORS (dataMessageGUID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)

CREATE TABLE salfordMove.dbo.PENDING_CHANGES(
	changeID INT NOT NULL,
	dataMessageGUID GUID NOT NULL,
	pendingChange BIT,
	CONSTRAINT PK_PENDING_CHANGES PRIMARY KEY (changeID),
	CONSTRAINT FK_PENDING_CHANGES_GUID FOREIGN KEY (dataMessageGUID)
	REFERENCES salfordMove.dbo.SENSORS (dataMessageGUID)
	ON DELETE CASCADE
	ON UPDATE CASCADE 
)

CREATE TABLE salfordMove.dbo.SENSOR_VOLTAGE(
	voltageID INT NOT NULL,
	dataMessageGUID GUID NOT NULL,
	voltage FLOAT,
	CONSTRAINT PK_SENSOR_VOLTAGE PRIMARY KEY (voltageID),
	CONSTRAINT FK_SENSOR_VOLTAGE_GUID FOREIGN KEY (dataMessageGUID)
	REFERENCES salfordMove.dbo.SENSORS (dataMessageGUID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
