TRUNCATE TABLE salfordMove.dbo.SENSOR_VOLTAGE;
TRUNCATE TABLE salfordMove.dbo.PENDING_CHANGES;
TRUNCATE TABLE salfordMove.dbo.BATTERY_STATUS;
TRUNCATE TABLE salfordMove.dbo.SIGNAL_STATUS;
TRUNCATE TABLE salfordMove.dbo.READINGS;
TRUNCATE TABLE salfordMove.dbo.DATA_TYPES;
TRUNCATE TABLE salfordMove.dbo.PLOT_LABELS;
TRUNCATE TABLE salfordMove.dbo.SENSORS;
TRUNCATE TABLE salfordMove.dbo.NETWORKS;
TRUNCATE TABLE salfordMove.dbo.APPLICATIONS;
GO