DROP TABLE salfordMove.dbo.SENSOR_VOLTAGE;
DROP TABLE salfordMove.dbo.PENDING_CHANGES;
DROP TABLE salfordMove.dbo.BATTERY_STATUS;
DROP TABLE salfordMove.dbo.SIGNAL_STATUS;
DROP TABLE salfordMove.dbo.READINGS;
DROP TABLE salfordMove.dbo.DATA_TYPES;
DROP TABLE salfordMove.dbo.PLOT_LABELS;
DROP TABLE salfordMove.dbo.SENSORS;
DROP TABLE salfordMove.dbo.NETWORKS;
DROP TABLE salfordMove.dbo.APPLICATIONS;
GO