DROP PROCEDURE PROC_GET_OR_CREATE_NETWORK;

DROP PROCEDURE PROC_GET_OR_CREATE_APPLICATION;

DROP PROCEDURE PROC_GET_OR_CREATE_SENSOR;

DROP PROCEDURE PROC_GET_OR_CREATE_DATA_TYPE;

DROP PROCEDURE PROC_GET_OR_CREATE_PLOT_LABELS;

DROP PROCEDURE PROC_CREATE_READING;

DROP PROCEDURE PROC_CREATE_SIGNAL_STATUS;

DROP PROCEDURE PROC_CREATE_BATTERY_STATUS;

DROP PROCEDURE PROC_CREATE_PENDING_CHANGES;

DROP PROCEDURE PROC_CREATE_SENSOR_VOLTAGE;

GO